-d C:\Users\hra\Documents\github\wave_table_sound\gowin\wave_table_sound\impl\gwsynthesis\wave_table_sound.vg
-p GW1N-2-LQFP100-6
-pn GW1N-UV2LQ100C6/I5
-cst C:\Users\hra\Documents\github\wave_table_sound\gowin\wave_table_sound\src\wave_table_sound.cst
-cfg C:\Users\hra\Documents\github\wave_table_sound\gowin\wave_table_sound\impl\pnr\device.cfg
-sdc C:\Users\hra\Documents\github\wave_table_sound\gowin\wave_table_sound\src\wave_table_sound.sdc
-bit
-tr
-ph
-timing
